# The next line updates PATH for the Google Cloud SDK.
if [ -f $HOME/.bin/google-cloud-sdk/path.zsh.inc ]; then . $HOME/bin/google-cloud-sdk/path.zsh.inc; fi

# The next line enables shell command completion for gcloud.
if [ -f $HOME/.bin/google-cloud-sdk/completion.zsh.inc ]; then . $HOME/.bin/google-cloud-sdk/completion.zsh.inc; fi

# Path for every ZSH run
export PATH=~/.bin:~/.brew/bin$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# oh-my-zsh plugins
plugins=(
git
osx
emoji
gcloud
docker
virtualenv
colored-man-pages
)

# Homebrew options.
export HOMEBREW_CASK_OPTS="--caskroom=$HOME/.brew/cask/ --appdir=~/Applications"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="radvan"

# Enable command auto-correction.
ENABLE_CORRECTION="false"

source $ZSH/oh-my-zsh.sh
source $HOME/.bin/google-cloud-sdk/completion.zsh.inc
source $HOME/.bin/google-cloud-sdk/path.zsh.inc
